package com.deepaksah.marrow.rebuild

enum class MarrowRoute(val parent: MarrowRoute? = null) {
    HOME,
    QBANK(HOME), QBANK_TRACKER(QBANK), QBANK_MODULE(QBANK), QBANK_LESSON(QBANK_MODULE), QBANK_PLAY(QBANK_LESSON),
    QBANK_SCORE(QBANK_PLAY), QBANK_REVIEW(QBANK_SCORE), QBANK_ANALYTICS(QBANK_SCORE), QBANK_TRACKER(QBANK),
    TESTS(HOME), TEST_INTRO(TESTS), TEST_PLAY(TEST_INTRO), TEST_SCORE(TEST_PLAY), TEST_REVIEW(TEST_SCORE), TEST_ANALYTICS(TEST_SCORE),
    VIDEOS(HOME), VIDEO_SUBJECT(VIDEOS), VIDEO_PLAYER(VIDEO_SUBJECT),
    CUSTOM_MODULE(QBANK), CUSTOM_INTRO(CUSTOM_MODULE), CUSTOM_CREATION(CUSTOM_MODULE),
    CUSTOM_MODE(CUSTOM_CREATION), CUSTOM_SUBJECTS(CUSTOM_MODE), CUSTOM_TOPICS(CUSTOM_SUBJECTS),
    CUSTOM_TAGS(CUSTOM_TOPICS), CUSTOM_ADDONS(CUSTOM_TAGS), CUSTOM_JOIN(CUSTOM_MODULE),
    CUSTOM_PLAY(CUSTOM_MODULE), CUSTOM_SCORE(CUSTOM_PLAY),
    PROFILE(HOME), SETTINGS(PROFILE), THEME(SETTINGS),
    SCHEMA(QBANK), SCHEMA_DETAIL(SCHEMA), SCHEMA_REVIEW(SCHEMA_DETAIL),
    BOOKMARKS(QBANK), SEARCH(QBANK), PYQ(QBANK), PEARLS(HOME)
}
