package kotlin;

import java.util.HashMap;
import kotlin.Metadata;

/* JADX INFO: loaded from: classes.dex */
@Metadata(d1 = {"\u0000\u001a\n\u0000\n\u0002\u0010\u000e\n\u0002\u0018\u0002\n\u0002\b\u0005\n\u0002\u0018\u0002\n\u0002\u0018\u0002\n\u0002\b\u0003\"\u001e\u0010\u0000\u001a\u00020\u0001*\u00020\u00028@X\u0080\u0004¢\u0006\f\u0012\u0004\b\u0003\u0010\u0004\u001a\u0004\b\u0005\u0010\u0006\"0\u0010\u0007\u001a\u001e\u0012\u0004\u0012\u00020\u0002\u0012\u0004\u0012\u00020\u00010\bj\u000e\u0012\u0004\u0012\u00020\u0002\u0012\u0004\u0012\u00020\u0001`\tX\u0082\u0004¢\u0006\b\n\u0000\u0012\u0004\b\n\u0010\u000b¨\u0006\f"}, d2 = {"androidType", "", "Landroidx/compose/ui/autofill/AutofillType;", "getAndroidType$annotations", "(Landroidx/compose/ui/autofill/AutofillType;)V", "getAndroidType", "(Landroidx/compose/ui/autofill/AutofillType;)Ljava/lang/String;", "androidAutofillTypes", "Ljava/util/HashMap;", "Lkotlin/collections/HashMap;", "getAndroidAutofillTypes$annotations", "()V", "ui"}, k = 2, mv = {2, 0, 0}, xi = 48)
public final class _skipCR {
    private static final HashMap<_writeQuotedLong, String> AudioAttributesCompatParcelizer = VideoTimelineResponseBody.AudioAttributesCompatParcelizer(setAction.write(_writeQuotedLong.onAddQueueItem, "emailAddress"), setAction.write(_writeQuotedLong.onSetRating, "username"), setAction.write(_writeQuotedLong.MediaControllerCompatMediaControllerImplApi21ExtraBinderRequestResultReceiver, "password"), setAction.write(_writeQuotedLong.handleMediaPlayPauseIfPendingOnHandler, "newUsername"), setAction.write(_writeQuotedLong.onCommand, "newPassword"), setAction.write(_writeQuotedLong.onPrepareFromUri, "postalAddress"), setAction.write(_writeQuotedLong.onRemoveQueueItemAt, "postalCode"), setAction.write(_writeQuotedLong.MediaBrowserCompatMediaItem, "creditCardNumber"), setAction.write(_writeQuotedLong.MediaBrowserCompatSearchResultReceiver, "creditCardSecurityCode"), setAction.write(_writeQuotedLong.MediaBrowserCompatCustomActionResultReceiver, "creditCardExpirationDate"), setAction.write(_writeQuotedLong.RatingCompat, "creditCardExpirationMonth"), setAction.write(_writeQuotedLong.MediaDescriptionCompat, "creditCardExpirationYear"), setAction.write(_writeQuotedLong.MediaMetadataCompat, "creditCardExpirationDay"), setAction.write(_writeQuotedLong.write, "addressCountry"), setAction.write(_writeQuotedLong.read, "addressRegion"), setAction.write(_writeQuotedLong.IconCompatParcelizer, "addressLocality"), setAction.write(_writeQuotedLong.AudioAttributesCompatParcelizer, "streetAddress"), setAction.write(_writeQuotedLong.RemoteActionCompatParcelizer, "extendedAddress"), setAction.write(_writeQuotedLong.onRewind, "extendedPostalCode"), setAction.write(_writeQuotedLong.onPause, "personName"), setAction.write(_writeQuotedLong.onPlay, "personGivenName"), setAction.write(_writeQuotedLong.onFastForward, "personFamilyName"), setAction.write(_writeQuotedLong.onMediaButtonEvent, "personMiddleName"), setAction.write(_writeQuotedLong.onPlayFromMediaId, "personMiddleInitial"), setAction.write(_writeQuotedLong.onPlayFromUri, "personNamePrefix"), setAction.write(_writeQuotedLong.onPrepareFromSearch, "personNameSuffix"), setAction.write(_writeQuotedLong.onPlayFromSearch, "phoneNumber"), setAction.write(_writeQuotedLong.onPrepare, "phoneNumberDevice"), setAction.write(_writeQuotedLong.onPrepareFromMediaId, "phoneCountryCode"), setAction.write(_writeQuotedLong.onRemoveQueueItem, "phoneNational"), setAction.write(_writeQuotedLong.onCustomAction, "gender"), setAction.write(_writeQuotedLong.AudioAttributesImplBaseParcelizer, "birthDateFull"), setAction.write(_writeQuotedLong.AudioAttributesImplApi26Parcelizer, "birthDateDay"), setAction.write(_writeQuotedLong.MediaBrowserCompatItemReceiver, "birthDateMonth"), setAction.write(_writeQuotedLong.AudioAttributesImplApi21Parcelizer, "birthDateYear"), setAction.write(_writeQuotedLong.onSeekTo, "smsOTPCode"));

    public static final String read(_writeQuotedLong _writequotedlong) {
        String str = AudioAttributesCompatParcelizer.get(_writequotedlong);
        if (str != null) {
            return str;
        }
        throw new IllegalArgumentException("Unsupported autofill type".toString());
    }
}
