package kotlin;

import android.app.ActivityManager;
import android.content.ContentResolver;
import android.content.Context;
import android.content.pm.PackageManager;
import android.hardware.SensorManager;
import android.hardware.input.InputManager;
import android.location.Geocoder;
import android.location.LocationManager;
import android.net.ConnectivityManager;
import android.os.StatFs;
import android.os.UserManager;
import android.telephony.TelephonyManager;
import com.fingerprintjs.android.fpjs_pro_internal.J2;
import java.util.List;

/* JADX INFO: loaded from: classes2.dex */
public final class AudioRendererEventListenerEventDispatcherExternalSyntheticLambda4 {
    public final onOutputStreamOffsetUsChanged AudioAttributesCompatParcelizer;
    public final List AudioAttributesImplApi21Parcelizer;
    public final parseTrueHdSyncframeAudioSampleCount AudioAttributesImplApi26Parcelizer;
    public final String AudioAttributesImplBaseParcelizer;
    public final getMeanBandwidth IconCompatParcelizer;
    public final boolean MediaBrowserCompatCustomActionResultReceiver;
    public final playPendingData MediaBrowserCompatItemReceiver;
    public final UserManager MediaBrowserCompatMediaItem;
    public final List MediaBrowserCompatSearchResultReceiver;
    public final String MediaControllerCompatMediaControllerImplApi21ExtraBinderRequestResultReceiver;
    public final SensorManager MediaDescriptionCompat;
    public final ContentResolver MediaMetadataCompat;
    public final PackageManager RatingCompat;
    public final isPausedState RemoteActionCompatParcelizer;
    public final newEncryptedObject handleMediaPlayPauseIfPendingOnHandler;
    public final isInvalidJoinTransition onAddQueueItem;
    public final String onCommand;
    public final String onCustomAction;
    public final releaseOutputBuffer onFastForward;
    public final parseAudioSpecificConfig onMediaButtonEvent;
    public final DefaultAudioTrackBufferSizeProvider onPause;
    public final processOutputBuffer onPlay;
    public final isLittleEndianFrameHeader onPlayFromMediaId;
    public final isSafeToMultiply onPlayFromSearch;
    public final DefaultAudioSinkMediaPositionParameters onPlayFromUri;
    public final supportsEncoding onPrepare;
    public final isIdentity onPrepareFromMediaId;
    public final newNoDataInstance onPrepareFromSearch;
    public final ChannelMappingAudioProcessor onPrepareFromUri;
    public final hasPendingData onRemoveQueueItemAt;
    public final hasAdvancingTimestamp onRewind;
    public final getFinalOutputBufferIndex read;
    public final isReadyState write;
    private static releaseOutputBuffer onSeekTo = new releaseOutputBuffer(false, 1500, 30, 5000, false, 1500, 30, 5000, true, true, 100, 1, false, true);
    private static DefaultAudioSinkExternalSyntheticLambda0 onRemoveQueueItem = DefaultAudioSinkExternalSyntheticLambda0.read;

    public AudioRendererEventListenerEventDispatcherExternalSyntheticLambda4(Context context, List list, String str, boolean z, List list2, boolean z2, long j) {
        UserManager userManager = (UserManager) setForHeaderData.read(onProcessedStreamChange.AudioAttributesCompatParcelizer(0L, new Ac3UtilSyncFrameInfo(context), 7), null);
        SensorManager sensorManager = (SensorManager) setForHeaderData.read(onProcessedStreamChange.AudioAttributesCompatParcelizer(0L, new parseAc4SyncframeSize(context), 7), null);
        PackageManager packageManager = (PackageManager) setForHeaderData.read(onProcessedStreamChange.AudioAttributesCompatParcelizer(0L, new AudioAttributesAudioAttributesV21(context), 7), null);
        ContentResolver contentResolver = (ContentResolver) setForHeaderData.read(onProcessedStreamChange.AudioAttributesCompatParcelizer(0L, new AudioCapabilitiesApi29(context), 7), null);
        ConnectivityManager connectivityManager = (ConnectivityManager) setForHeaderData.read(onProcessedStreamChange.AudioAttributesCompatParcelizer(0L, new AudioCapabilitiesReceiverAudioDeviceCallbackV23(context), 7), null);
        String str2 = (String) setForHeaderData.read(onProcessedStreamChange.AudioAttributesCompatParcelizer(0L, new AudioCapabilitiesReceiverListener(context), 7), null);
        LocationManager locationManager = (LocationManager) setForHeaderData.read(onProcessedStreamChange.AudioAttributesCompatParcelizer(0L, new isActive(context), 7), null);
        TelephonyManager telephonyManager = (TelephonyManager) setForHeaderData.read(onProcessedStreamChange.AudioAttributesCompatParcelizer(0L, new AudioRendererEventListener(context), 7), null);
        Geocoder geocoder = (Geocoder) setForHeaderData.read(onProcessedStreamChange.AudioAttributesCompatParcelizer(0L, new lambdadecoderInitialized1comgoogleandroidexoplayer2audioAudioRendererEventListenerEventDispatcher(context), 7), null);
        String str3 = (String) setForHeaderData.read(onProcessedStreamChange.AudioAttributesCompatParcelizer(0L, new AacUtilConfig(context), 7), null);
        isInvalidJoinTransition isinvalidjointransition = new isInvalidJoinTransition();
        String strWrite = resetTrimmedFrameCount.RemoteActionCompatParcelizer.write();
        newEncryptedObject newencryptedobject = AacUtil.AudioAttributesCompatParcelizer;
        DefaultAudioTrackBufferSizeProvider defaultAudioTrackBufferSizeProvider = new DefaultAudioTrackBufferSizeProvider();
        onAudioCapabilitiesChanged onaudiocapabilitieschanged = new onAudioCapabilitiesChanged();
        Object objWrite = r8lambdamCEi04OcFi8gu0FD463twzV2nG8.write(1000L, true, true, new createAudioTrackV29(context));
        ActivityManager activityManager = (ActivityManager) (C0177getRfBanners.RemoteActionCompatParcelizer(objWrite) ? null : objWrite);
        Object objWrite2 = r8lambdamCEi04OcFi8gu0FD463twzV2nG8.write(1000L, true, true, DefaultAudioSinkPendingExceptionHolder.write);
        StatFs statFs = (StatFs) (C0177getRfBanners.RemoteActionCompatParcelizer(objWrite2) ? null : objWrite2);
        Object objWrite3 = r8lambdamCEi04OcFi8gu0FD463twzV2nG8.write(1000L, true, true, new onDataRequest(context));
        getRebufferRate getrebufferrate = new getRebufferRate(activityManager, statFs);
        Object objWrite4 = r8lambdamCEi04OcFi8gu0FD463twzV2nG8.write(1000L, true, true, new getDtsFrameSize(context));
        XmpData xmpData = new XmpData((SensorManager) (C0177getRfBanners.RemoteActionCompatParcelizer(objWrite4) ? null : objWrite4));
        Object objWrite5 = r8lambdamCEi04OcFi8gu0FD463twzV2nG8.write(1000L, true, true, new DefaultAudioSinkAudioTrackBufferSizeProvider(context));
        getMeanInitialAudioFormatBitrate getmeaninitialaudioformatbitrate = new getMeanInitialAudioFormatBitrate((InputManager) (C0177getRfBanners.RemoteActionCompatParcelizer(objWrite5) ? null : objWrite5));
        DefaultAudioSinkDefaultAudioProcessorChain defaultAudioSinkDefaultAudioProcessorChain = new DefaultAudioSinkDefaultAudioProcessorChain(context);
        featureAndInstanceUidArguments featureandinstanceuidarguments = new featureAndInstanceUidArguments();
        Object objWrite6 = r8lambdamCEi04OcFi8gu0FD463twzV2nG8.write(1000L, true, true, new processBuffers(context));
        processOutputBuffer processoutputbuffer = new processOutputBuffer(onaudiocapabilitieschanged, getrebufferrate, xmpData, getmeaninitialaudioformatbitrate, defaultAudioSinkDefaultAudioProcessorChain, featureandinstanceuidarguments, new processSilence((ActivityManager) (C0177getRfBanners.RemoteActionCompatParcelizer(objWrite6) ? null : objWrite6)), new register());
        Object objWrite7 = r8lambdamCEi04OcFi8gu0FD463twzV2nG8.write(1000L, true, true, new useAudioTrackPlaybackParams(context));
        ToFloatPcmAudioProcessor toFloatPcmAudioProcessor = new ToFloatPcmAudioProcessor((ContentResolver) (C0177getRfBanners.RemoteActionCompatParcelizer(objWrite7) ? null : objWrite7));
        Object objWrite8 = r8lambdamCEi04OcFi8gu0FD463twzV2nG8.write(1000L, true, true, new getSubmittedFrames(context));
        isLittleEndianFrameHeader islittleendianframeheader = new isLittleEndianFrameHeader(toFloatPcmAudioProcessor, new DecoderAudioRendererApi23((ContentResolver) (C0177getRfBanners.RemoteActionCompatParcelizer(objWrite8) ? null : objWrite8)), new reportTrackChangeEvent());
        releaseOutputBuffer releaseoutputbuffer = onSeekTo;
        DefaultAudioSinkExternalSyntheticLambda0 defaultAudioSinkExternalSyntheticLambda0 = onRemoveQueueItem;
        isSafeToMultiply issafetomultiply = new isSafeToMultiply(context, connectivityManager);
        supportsEncoding supportsencoding = new supportsEncoding();
        isIdentity isidentity = new isIdentity();
        maybePrepareFile maybepreparefile = new maybePrepareFile(context, locationManager, geocoder);
        DefaultAudioSinkMediaPositionParameters defaultAudioSinkMediaPositionParameters = new DefaultAudioSinkMediaPositionParameters(context, locationManager);
        newNoDataInstance newnodatainstance = new newNoDataInstance(context);
        ChannelMappingAudioProcessor channelMappingAudioProcessor = new ChannelMappingAudioProcessor(maybepreparefile, newnodatainstance);
        hasPendingData haspendingdata = new hasPendingData(maybepreparefile, newnodatainstance, z2, j);
        hasAdvancingTimestamp hasadvancingtimestamp = new hasAdvancingTimestamp(telephonyManager);
        getSkippedFrames getskippedframes = new getSkippedFrames(str3);
        onOutputStreamOffsetUsChanged onoutputstreamoffsetuschanged = new onOutputStreamOffsetUsChanged(new doLicense(getskippedframes, setVolumeInternalV21.IconCompatParcelizer.write(), new isEncrypted()));
        isPausedState ispausedstate = new isPausedState();
        isReadyState isreadystate = new isReadyState(new PlaybackStatsListenerCallback());
        getFinalOutputBufferIndex getfinaloutputbufferindex = new getFinalOutputBufferIndex(new unregister());
        playPendingData playpendingdata = new playPendingData(packageManager, str2);
        parseTrueHdSyncframeAudioSampleCount parsetruehdsyncframeaudiosamplecount = new parseTrueHdSyncframeAudioSampleCount(new J2());
        this.AudioAttributesImplApi21Parcelizer = list;
        this.AudioAttributesImplBaseParcelizer = str;
        this.MediaBrowserCompatCustomActionResultReceiver = z;
        this.MediaBrowserCompatSearchResultReceiver = list2;
        this.MediaBrowserCompatMediaItem = userManager;
        this.MediaDescriptionCompat = sensorManager;
        this.RatingCompat = packageManager;
        this.MediaMetadataCompat = contentResolver;
        this.onCommand = str2;
        this.onAddQueueItem = isinvalidjointransition;
        this.onCustomAction = "2.10.0";
        this.MediaControllerCompatMediaControllerImplApi21ExtraBinderRequestResultReceiver = strWrite;
        this.handleMediaPlayPauseIfPendingOnHandler = newencryptedobject;
        this.onPause = defaultAudioTrackBufferSizeProvider;
        this.onPlay = processoutputbuffer;
        this.onPlayFromMediaId = islittleendianframeheader;
        this.onFastForward = releaseoutputbuffer;
        this.onMediaButtonEvent = defaultAudioSinkExternalSyntheticLambda0;
        this.onPlayFromSearch = issafetomultiply;
        this.onPrepare = supportsencoding;
        this.onPrepareFromMediaId = isidentity;
        this.onPlayFromUri = defaultAudioSinkMediaPositionParameters;
        this.onPrepareFromSearch = newnodatainstance;
        this.onPrepareFromUri = channelMappingAudioProcessor;
        this.onRemoveQueueItemAt = haspendingdata;
        this.onRewind = hasadvancingtimestamp;
        this.IconCompatParcelizer = getskippedframes;
        this.AudioAttributesCompatParcelizer = onoutputstreamoffsetuschanged;
        this.RemoteActionCompatParcelizer = ispausedstate;
        this.write = isreadystate;
        this.read = getfinaloutputbufferindex;
        this.MediaBrowserCompatItemReceiver = playpendingdata;
        this.AudioAttributesImplApi26Parcelizer = parsetruehdsyncframeaudiosamplecount;
    }
}
