package kotlin;

import java.util.ArrayList;
import java.util.List;
import org.apache.commons.compress.archivers.zip.UnixStat;

/* JADX INFO: loaded from: classes3.dex */
public final class getListenerKey {
    public static final IStatusCallback AudioAttributesCompatParcelizer(LogLogger1 logLogger1) {
        toMagicModuleMetaRepoModel.write(logLogger1, "");
        IStatusCallback iStatusCallback = new IStatusCallback(null, null, null, null, null, null, null, null, null, UnixStat.DEFAULT_LINK_PERM, null);
        if (logLogger1.MediaBrowserCompatCustomActionResultReceiver().length() > 0) {
            iStatusCallback = IStatusCallback.RemoteActionCompatParcelizer((510 & 1) != 0 ? iStatusCallback.AudioAttributesImplBaseParcelizer : logLogger1.MediaBrowserCompatCustomActionResultReceiver(), (510 & 2) != 0 ? iStatusCallback.RemoteActionCompatParcelizer : null, (510 & 4) != 0 ? iStatusCallback.AudioAttributesCompatParcelizer : null, (510 & 8) != 0 ? iStatusCallback.write : null, (510 & 16) != 0 ? iStatusCallback.read : null, (510 & 32) != 0 ? iStatusCallback.IconCompatParcelizer : null, (510 & 64) != 0 ? iStatusCallback.AudioAttributesImplApi26Parcelizer : null, (510 & 128) != 0 ? iStatusCallback.MediaBrowserCompatCustomActionResultReceiver : null, (510 & 256) != 0 ? iStatusCallback.MediaBrowserCompatItemReceiver : null);
        }
        IStatusCallback iStatusCallbackRemoteActionCompatParcelizer = iStatusCallback;
        if (logLogger1.read().length() > 0) {
            iStatusCallbackRemoteActionCompatParcelizer = IStatusCallback.RemoteActionCompatParcelizer((510 & 1) != 0 ? iStatusCallbackRemoteActionCompatParcelizer.AudioAttributesImplBaseParcelizer : null, (510 & 2) != 0 ? iStatusCallbackRemoteActionCompatParcelizer.RemoteActionCompatParcelizer : logLogger1.read(), (510 & 4) != 0 ? iStatusCallbackRemoteActionCompatParcelizer.AudioAttributesCompatParcelizer : null, (510 & 8) != 0 ? iStatusCallbackRemoteActionCompatParcelizer.write : null, (510 & 16) != 0 ? iStatusCallbackRemoteActionCompatParcelizer.read : null, (510 & 32) != 0 ? iStatusCallbackRemoteActionCompatParcelizer.IconCompatParcelizer : null, (510 & 64) != 0 ? iStatusCallbackRemoteActionCompatParcelizer.AudioAttributesImplApi26Parcelizer : null, (510 & 128) != 0 ? iStatusCallbackRemoteActionCompatParcelizer.MediaBrowserCompatCustomActionResultReceiver : null, (510 & 256) != 0 ? iStatusCallbackRemoteActionCompatParcelizer.MediaBrowserCompatItemReceiver : null);
        }
        IStatusCallback iStatusCallbackRemoteActionCompatParcelizer2 = iStatusCallbackRemoteActionCompatParcelizer;
        if (logLogger1.AudioAttributesCompatParcelizer().length() > 0) {
            iStatusCallbackRemoteActionCompatParcelizer2 = IStatusCallback.RemoteActionCompatParcelizer((510 & 1) != 0 ? iStatusCallbackRemoteActionCompatParcelizer2.AudioAttributesImplBaseParcelizer : null, (510 & 2) != 0 ? iStatusCallbackRemoteActionCompatParcelizer2.RemoteActionCompatParcelizer : null, (510 & 4) != 0 ? iStatusCallbackRemoteActionCompatParcelizer2.AudioAttributesCompatParcelizer : logLogger1.AudioAttributesCompatParcelizer(), (510 & 8) != 0 ? iStatusCallbackRemoteActionCompatParcelizer2.write : null, (510 & 16) != 0 ? iStatusCallbackRemoteActionCompatParcelizer2.read : null, (510 & 32) != 0 ? iStatusCallbackRemoteActionCompatParcelizer2.IconCompatParcelizer : null, (510 & 64) != 0 ? iStatusCallbackRemoteActionCompatParcelizer2.AudioAttributesImplApi26Parcelizer : null, (510 & 128) != 0 ? iStatusCallbackRemoteActionCompatParcelizer2.MediaBrowserCompatCustomActionResultReceiver : null, (510 & 256) != 0 ? iStatusCallbackRemoteActionCompatParcelizer2.MediaBrowserCompatItemReceiver : null);
        }
        IStatusCallback iStatusCallbackRemoteActionCompatParcelizer3 = iStatusCallbackRemoteActionCompatParcelizer2;
        if (logLogger1.write().length() > 0) {
            iStatusCallbackRemoteActionCompatParcelizer3 = IStatusCallback.RemoteActionCompatParcelizer((510 & 1) != 0 ? iStatusCallbackRemoteActionCompatParcelizer3.AudioAttributesImplBaseParcelizer : null, (510 & 2) != 0 ? iStatusCallbackRemoteActionCompatParcelizer3.RemoteActionCompatParcelizer : null, (510 & 4) != 0 ? iStatusCallbackRemoteActionCompatParcelizer3.AudioAttributesCompatParcelizer : null, (510 & 8) != 0 ? iStatusCallbackRemoteActionCompatParcelizer3.write : null, (510 & 16) != 0 ? iStatusCallbackRemoteActionCompatParcelizer3.read : null, (510 & 32) != 0 ? iStatusCallbackRemoteActionCompatParcelizer3.IconCompatParcelizer : logLogger1.write(), (510 & 64) != 0 ? iStatusCallbackRemoteActionCompatParcelizer3.AudioAttributesImplApi26Parcelizer : null, (510 & 128) != 0 ? iStatusCallbackRemoteActionCompatParcelizer3.MediaBrowserCompatCustomActionResultReceiver : null, (510 & 256) != 0 ? iStatusCallbackRemoteActionCompatParcelizer3.MediaBrowserCompatItemReceiver : null);
        }
        IStatusCallback iStatusCallbackRemoteActionCompatParcelizer4 = iStatusCallbackRemoteActionCompatParcelizer3;
        if (logLogger1.IconCompatParcelizer().length() > 0) {
            iStatusCallbackRemoteActionCompatParcelizer4 = IStatusCallback.RemoteActionCompatParcelizer((510 & 1) != 0 ? iStatusCallbackRemoteActionCompatParcelizer4.AudioAttributesImplBaseParcelizer : null, (510 & 2) != 0 ? iStatusCallbackRemoteActionCompatParcelizer4.RemoteActionCompatParcelizer : null, (510 & 4) != 0 ? iStatusCallbackRemoteActionCompatParcelizer4.AudioAttributesCompatParcelizer : null, (510 & 8) != 0 ? iStatusCallbackRemoteActionCompatParcelizer4.write : null, (510 & 16) != 0 ? iStatusCallbackRemoteActionCompatParcelizer4.read : null, (510 & 32) != 0 ? iStatusCallbackRemoteActionCompatParcelizer4.IconCompatParcelizer : null, (510 & 64) != 0 ? iStatusCallbackRemoteActionCompatParcelizer4.AudioAttributesImplApi26Parcelizer : logLogger1.IconCompatParcelizer(), (510 & 128) != 0 ? iStatusCallbackRemoteActionCompatParcelizer4.MediaBrowserCompatCustomActionResultReceiver : null, (510 & 256) != 0 ? iStatusCallbackRemoteActionCompatParcelizer4.MediaBrowserCompatItemReceiver : null);
        }
        IStatusCallback iStatusCallbackRemoteActionCompatParcelizer5 = iStatusCallbackRemoteActionCompatParcelizer4;
        if (logLogger1.MediaBrowserCompatItemReceiver().length() > 0) {
            iStatusCallbackRemoteActionCompatParcelizer5 = IStatusCallback.RemoteActionCompatParcelizer((510 & 1) != 0 ? iStatusCallbackRemoteActionCompatParcelizer5.AudioAttributesImplBaseParcelizer : null, (510 & 2) != 0 ? iStatusCallbackRemoteActionCompatParcelizer5.RemoteActionCompatParcelizer : null, (510 & 4) != 0 ? iStatusCallbackRemoteActionCompatParcelizer5.AudioAttributesCompatParcelizer : null, (510 & 8) != 0 ? iStatusCallbackRemoteActionCompatParcelizer5.write : null, (510 & 16) != 0 ? iStatusCallbackRemoteActionCompatParcelizer5.read : null, (510 & 32) != 0 ? iStatusCallbackRemoteActionCompatParcelizer5.IconCompatParcelizer : null, (510 & 64) != 0 ? iStatusCallbackRemoteActionCompatParcelizer5.AudioAttributesImplApi26Parcelizer : null, (510 & 128) != 0 ? iStatusCallbackRemoteActionCompatParcelizer5.MediaBrowserCompatCustomActionResultReceiver : logLogger1.MediaBrowserCompatItemReceiver(), (510 & 256) != 0 ? iStatusCallbackRemoteActionCompatParcelizer5.MediaBrowserCompatItemReceiver : null);
        }
        IStatusCallback iStatusCallback2 = iStatusCallbackRemoteActionCompatParcelizer5;
        List<createFormatFromMediaFormat> listRemoteActionCompatParcelizer = logLogger1.RemoteActionCompatParcelizer();
        ArrayList arrayList = new ArrayList(IntermediateLoginResponseBody.RemoteActionCompatParcelizer((Iterable) listRemoteActionCompatParcelizer, 10));
        for (createFormatFromMediaFormat createformatfrommediaformat : listRemoteActionCompatParcelizer) {
            arrayList.add(new addCallback(createformatfrommediaformat.RemoteActionCompatParcelizer(), createformatfrommediaformat.write(), createformatfrommediaformat.IconCompatParcelizer()));
        }
        IStatusCallback iStatusCallbackRemoteActionCompatParcelizer6 = IStatusCallback.RemoteActionCompatParcelizer((510 & 1) != 0 ? iStatusCallback2.AudioAttributesImplBaseParcelizer : null, (510 & 2) != 0 ? iStatusCallback2.RemoteActionCompatParcelizer : null, (510 & 4) != 0 ? iStatusCallback2.AudioAttributesCompatParcelizer : null, (510 & 8) != 0 ? iStatusCallback2.write : null, (510 & 16) != 0 ? iStatusCallback2.read : arrayList, (510 & 32) != 0 ? iStatusCallback2.IconCompatParcelizer : null, (510 & 64) != 0 ? iStatusCallback2.AudioAttributesImplApi26Parcelizer : null, (510 & 128) != 0 ? iStatusCallback2.MediaBrowserCompatCustomActionResultReceiver : null, (510 & 256) != 0 ? iStatusCallback2.MediaBrowserCompatItemReceiver : null);
        List<MediaClock> listAudioAttributesImplBaseParcelizer = logLogger1.AudioAttributesImplBaseParcelizer();
        ArrayList arrayList2 = new ArrayList(IntermediateLoginResponseBody.RemoteActionCompatParcelizer((Iterable) listAudioAttributesImplBaseParcelizer, 10));
        for (MediaClock mediaClock : listAudioAttributesImplBaseParcelizer) {
            arrayList2.add(new LifecycleFragment(mediaClock.read(), mediaClock.write()));
        }
        return IStatusCallback.RemoteActionCompatParcelizer((510 & 1) != 0 ? iStatusCallbackRemoteActionCompatParcelizer6.AudioAttributesImplBaseParcelizer : null, (510 & 2) != 0 ? iStatusCallbackRemoteActionCompatParcelizer6.RemoteActionCompatParcelizer : null, (510 & 4) != 0 ? iStatusCallbackRemoteActionCompatParcelizer6.AudioAttributesCompatParcelizer : null, (510 & 8) != 0 ? iStatusCallbackRemoteActionCompatParcelizer6.write : null, (510 & 16) != 0 ? iStatusCallbackRemoteActionCompatParcelizer6.read : null, (510 & 32) != 0 ? iStatusCallbackRemoteActionCompatParcelizer6.IconCompatParcelizer : null, (510 & 64) != 0 ? iStatusCallbackRemoteActionCompatParcelizer6.AudioAttributesImplApi26Parcelizer : null, (510 & 128) != 0 ? iStatusCallbackRemoteActionCompatParcelizer6.MediaBrowserCompatCustomActionResultReceiver : null, (510 & 256) != 0 ? iStatusCallbackRemoteActionCompatParcelizer6.MediaBrowserCompatItemReceiver : arrayList2);
    }
}
