package kotlin;

/* JADX INFO: loaded from: classes2.dex */
public final class lambdaseekTo10 {
    private static final String AudioAttributesCompatParcelizer;
    private static final String AudioAttributesImplApi21Parcelizer;
    private static final String AudioAttributesImplApi26Parcelizer;
    private static final String AudioAttributesImplBaseParcelizer;
    private static final String IconCompatParcelizer;
    private static final String MediaBrowserCompatCustomActionResultReceiver;
    private static final String MediaBrowserCompatItemReceiver;
    private static final String MediaBrowserCompatMediaItem;
    private static final String MediaBrowserCompatSearchResultReceiver;
    private static final String MediaControllerCompatMediaControllerImplApi21ExtraBinderRequestResultReceiver;
    private static final String MediaDescriptionCompat;
    private static final String MediaMetadataCompat;
    private static final String RatingCompat;
    private static final String RemoteActionCompatParcelizer;
    private static final String handleMediaPlayPauseIfPendingOnHandler;
    private static final String onAddQueueItem;
    private static final String onCommand;
    private static final String onCustomAction;
    private static final String read;
    private static final String write;

    static {
        StringBuilder sb = new StringBuilder("\n    CREATE TABLE ");
        sb.append(lambdasetDeviceVolume23.RemoteActionCompatParcelizer.getAudioAttributesCompatParcelizer());
        sb.append(" (\n        _id INTEGER PRIMARY KEY AUTOINCREMENT,\n        data STRING NOT NULL,\n        created_at INTEGER NOT NULL\n    );\n");
        RemoteActionCompatParcelizer = sb.toString();
        StringBuilder sb2 = new StringBuilder("\n    CREATE TABLE ");
        sb2.append(lambdasetDeviceVolume23.MediaBrowserCompatCustomActionResultReceiver.getAudioAttributesCompatParcelizer());
        sb2.append(" (\n        deviceID STRING NOT NULL,\n        eventName STRING NOT NULL,\n        normalizedEventName STRING NOT NULL,\n        firstTs INTEGER NOT NULL,\n        lastTs INTEGER NOT NULL,\n        count INTEGER NOT NULL,\n        PRIMARY KEY (deviceID, normalizedEventName)\n    );\n");
        AudioAttributesImplApi21Parcelizer = sb2.toString();
        StringBuilder sb3 = new StringBuilder("\n    CREATE TABLE ");
        sb3.append(lambdasetDeviceVolume23.read.getAudioAttributesCompatParcelizer());
        sb3.append(" (\n        _id INTEGER PRIMARY KEY AUTOINCREMENT,\n        data STRING NOT NULL,\n        created_at INTEGER NOT NULL\n    );\n");
        read = sb3.toString();
        StringBuilder sb4 = new StringBuilder(" \n    CREATE TABLE ");
        sb4.append(lambdasetDeviceVolume23.write.getAudioAttributesCompatParcelizer());
        sb4.append(" (\n        _id STRING NOT NULL,\n        data TEXT NOT NULL,\n        wzrkParams TEXT NOT NULL,\n        campaignId STRING NOT NULL,\n        tags TEXT NOT NULL,\n        isRead INTEGER NOT NULL DEFAULT 0,\n        expires INTEGER NOT NULL,\n        created_at INTEGER NOT NULL,\n        messageUser STRING NOT NULL\n    );\n");
        AudioAttributesCompatParcelizer = sb4.toString();
        StringBuilder sb5 = new StringBuilder("\n    CREATE UNIQUE INDEX IF NOT EXISTS userid_id_idx ON ");
        sb5.append(lambdasetDeviceVolume23.write.getAudioAttributesCompatParcelizer());
        sb5.append(" (\n        messageUser,\n        _id\n    );\n");
        MediaBrowserCompatMediaItem = sb5.toString();
        StringBuilder sb6 = new StringBuilder("\n    CREATE INDEX IF NOT EXISTS time_idx ON ");
        sb6.append(lambdasetDeviceVolume23.RemoteActionCompatParcelizer.getAudioAttributesCompatParcelizer());
        sb6.append(" (created_at);\n");
        MediaMetadataCompat = sb6.toString();
        StringBuilder sb7 = new StringBuilder("\n    CREATE INDEX IF NOT EXISTS time_idx ON ");
        sb7.append(lambdasetDeviceVolume23.read.getAudioAttributesCompatParcelizer());
        sb7.append(" ( created_at);\n");
        onAddQueueItem = sb7.toString();
        StringBuilder sb8 = new StringBuilder("\n    CREATE TABLE ");
        sb8.append(lambdasetDeviceVolume23.IconCompatParcelizer.getAudioAttributesCompatParcelizer());
        sb8.append(" (\n        _id INTEGER PRIMARY KEY AUTOINCREMENT,\n        data STRING NOT NULL,\n        created_at INTEGER NOT NULL,\n        isRead INTEGER NOT NULL\n    );\n");
        IconCompatParcelizer = sb8.toString();
        StringBuilder sb9 = new StringBuilder("\n    CREATE INDEX IF NOT EXISTS time_idx ON ");
        sb9.append(lambdasetDeviceVolume23.IconCompatParcelizer.getAudioAttributesCompatParcelizer());
        sb9.append(" (created_at);\n");
        handleMediaPlayPauseIfPendingOnHandler = sb9.toString();
        StringBuilder sb10 = new StringBuilder("\n    CREATE TABLE ");
        sb10.append(lambdasetDeviceVolume23.AudioAttributesImplApi21Parcelizer.getAudioAttributesCompatParcelizer());
        sb10.append(" (\n        _id INTEGER PRIMARY KEY AUTOINCREMENT,\n        created_at INTEGER NOT NULL\n    );\n");
        AudioAttributesImplBaseParcelizer = sb10.toString();
        StringBuilder sb11 = new StringBuilder("\n    CREATE INDEX IF NOT EXISTS time_idx ON ");
        sb11.append(lambdasetDeviceVolume23.AudioAttributesImplApi21Parcelizer.getAudioAttributesCompatParcelizer());
        sb11.append(" (created_at);\n");
        onCustomAction = sb11.toString();
        StringBuilder sb12 = new StringBuilder("\n    CREATE TABLE ");
        sb12.append(lambdasetDeviceVolume23.AudioAttributesCompatParcelizer.getAudioAttributesCompatParcelizer());
        sb12.append(" (\n        _id INTEGER PRIMARY KEY AUTOINCREMENT,\n        data STRING NOT NULL,\n        created_at INTEGER NOT NULL\n    );\n");
        write = sb12.toString();
        StringBuilder sb13 = new StringBuilder("\n    CREATE INDEX IF NOT EXISTS time_idx ON ");
        sb13.append(lambdasetDeviceVolume23.AudioAttributesCompatParcelizer.getAudioAttributesCompatParcelizer());
        sb13.append(" (created_at);\n");
        MediaControllerCompatMediaControllerImplApi21ExtraBinderRequestResultReceiver = sb13.toString();
        StringBuilder sb14 = new StringBuilder("DROP TABLE IF EXISTS ");
        sb14.append(lambdasetDeviceVolume23.AudioAttributesImplApi21Parcelizer.getAudioAttributesCompatParcelizer());
        MediaBrowserCompatSearchResultReceiver = sb14.toString();
        StringBuilder sb15 = new StringBuilder("DROP TABLE IF EXISTS ");
        sb15.append(lambdasetDeviceVolume23.write.getAudioAttributesCompatParcelizer());
        AudioAttributesImplApi26Parcelizer = sb15.toString();
        StringBuilder sb16 = new StringBuilder("DROP TABLE IF EXISTS ");
        sb16.append(lambdasetDeviceVolume23.AudioAttributesCompatParcelizer.getAudioAttributesCompatParcelizer());
        MediaDescriptionCompat = sb16.toString();
        StringBuilder sb17 = new StringBuilder("\n    CREATE TABLE ");
        sb17.append(lambdasetDeviceVolume23.MediaBrowserCompatItemReceiver.getAudioAttributesCompatParcelizer());
        sb17.append(" (\n        deviceID STRING NOT NULL,\n        _id STRING NOT NULL,\n        data STRING NOT NULL,\n        PRIMARY KEY (_id, deviceID)\n    );\n");
        MediaBrowserCompatCustomActionResultReceiver = sb17.toString();
        StringBuilder sb18 = new StringBuilder("\n    CREATE TABLE temp_");
        sb18.append(lambdasetDeviceVolume23.MediaBrowserCompatItemReceiver.getAudioAttributesCompatParcelizer());
        sb18.append(" (\n        _id STRING NOT NULL,\n        deviceID STRING NOT NULL,\n        data STRING NOT NULL,\n        PRIMARY KEY (_id, deviceID)\n    );\n");
        MediaBrowserCompatItemReceiver = sb18.toString();
        StringBuilder sb19 = new StringBuilder("\n    DROP TABLE ");
        sb19.append(lambdasetDeviceVolume23.MediaBrowserCompatItemReceiver.getAudioAttributesCompatParcelizer());
        sb19.append(";\n");
        RatingCompat = sb19.toString();
        StringBuilder sb20 = new StringBuilder("\n    ALTER TABLE temp_");
        sb20.append(lambdasetDeviceVolume23.MediaBrowserCompatItemReceiver.getAudioAttributesCompatParcelizer());
        sb20.append(" RENAME TO ");
        sb20.append(lambdasetDeviceVolume23.MediaBrowserCompatItemReceiver.getAudioAttributesCompatParcelizer());
        sb20.append(";\n");
        onCommand = sb20.toString();
    }
}
