package kotlin;

import com.google.android.exoplayer2.text.ttml.TtmlNode;
import java.util.Set;

/* JADX INFO: loaded from: classes4.dex */
public final class setSuggestedSubjects {
    public static final getRelatedLessonId AudioAttributesCompatParcelizer;
    public static final getRelatedLessonId AudioAttributesImplApi21Parcelizer;
    public static final getRelatedLessonId AudioAttributesImplApi26Parcelizer;
    public static final getRelatedLessonId AudioAttributesImplBaseParcelizer;
    public static final Set<getRelatedLessonId> IconCompatParcelizer;
    public static final getRelatedLessonId MediaBrowserCompatCustomActionResultReceiver;
    public static final getRelatedLessonId MediaBrowserCompatItemReceiver;
    public static final getRelatedLessonId MediaBrowserCompatMediaItem;
    public static final getRelatedLessonId MediaBrowserCompatSearchResultReceiver;
    public static final Set<getRelatedLessonId> MediaControllerCompatMediaControllerImplApi21ExtraBinderRequestResultReceiver;
    public static final getRelatedLessonId MediaDescriptionCompat;
    public static final getRelatedLessonId MediaMetadataCompat;
    public static final getRelatedLessonId RatingCompat;
    public static final newYearNameItem RemoteActionCompatParcelizer;
    public static final getRelatedLessonId handleMediaPlayPauseIfPendingOnHandler;
    public static final getRelatedLessonId onAddQueueItem;
    public static final getRelatedLessonId onCommand;
    public static final getRelatedLessonId onCustomAction;
    public static final getRelatedLessonId read;
    public static final Set<getRelatedLessonId> write;

    private setSuggestedSubjects() {
    }

    static {
        new setSuggestedSubjects();
        getRelatedLessonId getrelatedlessonidRemoteActionCompatParcelizer = getRelatedLessonId.RemoteActionCompatParcelizer("getValue");
        toMagicModuleMetaRepoModel.AudioAttributesCompatParcelizer(getrelatedlessonidRemoteActionCompatParcelizer, "");
        AudioAttributesImplApi26Parcelizer = getrelatedlessonidRemoteActionCompatParcelizer;
        getRelatedLessonId getrelatedlessonidRemoteActionCompatParcelizer2 = getRelatedLessonId.RemoteActionCompatParcelizer("setValue");
        toMagicModuleMetaRepoModel.AudioAttributesCompatParcelizer(getrelatedlessonidRemoteActionCompatParcelizer2, "");
        onCommand = getrelatedlessonidRemoteActionCompatParcelizer2;
        getRelatedLessonId getrelatedlessonidRemoteActionCompatParcelizer3 = getRelatedLessonId.RemoteActionCompatParcelizer("provideDelegate");
        toMagicModuleMetaRepoModel.AudioAttributesCompatParcelizer(getrelatedlessonidRemoteActionCompatParcelizer3, "");
        RatingCompat = getrelatedlessonidRemoteActionCompatParcelizer3;
        getRelatedLessonId getrelatedlessonidRemoteActionCompatParcelizer4 = getRelatedLessonId.RemoteActionCompatParcelizer("equals");
        toMagicModuleMetaRepoModel.AudioAttributesCompatParcelizer(getrelatedlessonidRemoteActionCompatParcelizer4, "");
        AudioAttributesImplBaseParcelizer = getrelatedlessonidRemoteActionCompatParcelizer4;
        toMagicModuleMetaRepoModel.AudioAttributesCompatParcelizer(getRelatedLessonId.RemoteActionCompatParcelizer("hashCode"), "");
        getRelatedLessonId getrelatedlessonidRemoteActionCompatParcelizer5 = getRelatedLessonId.RemoteActionCompatParcelizer("compareTo");
        toMagicModuleMetaRepoModel.AudioAttributesCompatParcelizer(getrelatedlessonidRemoteActionCompatParcelizer5, "");
        AudioAttributesCompatParcelizer = getrelatedlessonidRemoteActionCompatParcelizer5;
        getRelatedLessonId getrelatedlessonidRemoteActionCompatParcelizer6 = getRelatedLessonId.RemoteActionCompatParcelizer("contains");
        toMagicModuleMetaRepoModel.AudioAttributesCompatParcelizer(getrelatedlessonidRemoteActionCompatParcelizer6, "");
        read = getrelatedlessonidRemoteActionCompatParcelizer6;
        getRelatedLessonId getrelatedlessonidRemoteActionCompatParcelizer7 = getRelatedLessonId.RemoteActionCompatParcelizer("invoke");
        toMagicModuleMetaRepoModel.AudioAttributesCompatParcelizer(getrelatedlessonidRemoteActionCompatParcelizer7, "");
        MediaBrowserCompatMediaItem = getrelatedlessonidRemoteActionCompatParcelizer7;
        getRelatedLessonId getrelatedlessonidRemoteActionCompatParcelizer8 = getRelatedLessonId.RemoteActionCompatParcelizer("iterator");
        toMagicModuleMetaRepoModel.AudioAttributesCompatParcelizer(getrelatedlessonidRemoteActionCompatParcelizer8, "");
        MediaDescriptionCompat = getrelatedlessonidRemoteActionCompatParcelizer8;
        getRelatedLessonId getrelatedlessonidRemoteActionCompatParcelizer9 = getRelatedLessonId.RemoteActionCompatParcelizer("get");
        toMagicModuleMetaRepoModel.AudioAttributesCompatParcelizer(getrelatedlessonidRemoteActionCompatParcelizer9, "");
        AudioAttributesImplApi21Parcelizer = getrelatedlessonidRemoteActionCompatParcelizer9;
        getRelatedLessonId getrelatedlessonidRemoteActionCompatParcelizer10 = getRelatedLessonId.RemoteActionCompatParcelizer("set");
        toMagicModuleMetaRepoModel.AudioAttributesCompatParcelizer(getrelatedlessonidRemoteActionCompatParcelizer10, "");
        handleMediaPlayPauseIfPendingOnHandler = getrelatedlessonidRemoteActionCompatParcelizer10;
        getRelatedLessonId getrelatedlessonidRemoteActionCompatParcelizer11 = getRelatedLessonId.RemoteActionCompatParcelizer("next");
        toMagicModuleMetaRepoModel.AudioAttributesCompatParcelizer(getrelatedlessonidRemoteActionCompatParcelizer11, "");
        MediaBrowserCompatSearchResultReceiver = getrelatedlessonidRemoteActionCompatParcelizer11;
        getRelatedLessonId getrelatedlessonidRemoteActionCompatParcelizer12 = getRelatedLessonId.RemoteActionCompatParcelizer("hasNext");
        toMagicModuleMetaRepoModel.AudioAttributesCompatParcelizer(getrelatedlessonidRemoteActionCompatParcelizer12, "");
        MediaBrowserCompatItemReceiver = getrelatedlessonidRemoteActionCompatParcelizer12;
        toMagicModuleMetaRepoModel.AudioAttributesCompatParcelizer(getRelatedLessonId.RemoteActionCompatParcelizer("toString"), "");
        RemoteActionCompatParcelizer = new newYearNameItem("component\\d+");
        getRelatedLessonId getrelatedlessonidRemoteActionCompatParcelizer13 = getRelatedLessonId.RemoteActionCompatParcelizer("and");
        toMagicModuleMetaRepoModel.AudioAttributesCompatParcelizer(getrelatedlessonidRemoteActionCompatParcelizer13, "");
        getRelatedLessonId getrelatedlessonidRemoteActionCompatParcelizer14 = getRelatedLessonId.RemoteActionCompatParcelizer("or");
        toMagicModuleMetaRepoModel.AudioAttributesCompatParcelizer(getrelatedlessonidRemoteActionCompatParcelizer14, "");
        getRelatedLessonId getrelatedlessonidRemoteActionCompatParcelizer15 = getRelatedLessonId.RemoteActionCompatParcelizer("xor");
        toMagicModuleMetaRepoModel.AudioAttributesCompatParcelizer(getrelatedlessonidRemoteActionCompatParcelizer15, "");
        getRelatedLessonId getrelatedlessonidRemoteActionCompatParcelizer16 = getRelatedLessonId.RemoteActionCompatParcelizer("inv");
        toMagicModuleMetaRepoModel.AudioAttributesCompatParcelizer(getrelatedlessonidRemoteActionCompatParcelizer16, "");
        getRelatedLessonId getrelatedlessonidRemoteActionCompatParcelizer17 = getRelatedLessonId.RemoteActionCompatParcelizer("shl");
        toMagicModuleMetaRepoModel.AudioAttributesCompatParcelizer(getrelatedlessonidRemoteActionCompatParcelizer17, "");
        getRelatedLessonId getrelatedlessonidRemoteActionCompatParcelizer18 = getRelatedLessonId.RemoteActionCompatParcelizer("shr");
        toMagicModuleMetaRepoModel.AudioAttributesCompatParcelizer(getrelatedlessonidRemoteActionCompatParcelizer18, "");
        getRelatedLessonId getrelatedlessonidRemoteActionCompatParcelizer19 = getRelatedLessonId.RemoteActionCompatParcelizer("ushr");
        toMagicModuleMetaRepoModel.AudioAttributesCompatParcelizer(getrelatedlessonidRemoteActionCompatParcelizer19, "");
        getRelatedLessonId getrelatedlessonidRemoteActionCompatParcelizer20 = getRelatedLessonId.RemoteActionCompatParcelizer("inc");
        toMagicModuleMetaRepoModel.AudioAttributesCompatParcelizer(getrelatedlessonidRemoteActionCompatParcelizer20, "");
        MediaMetadataCompat = getrelatedlessonidRemoteActionCompatParcelizer20;
        getRelatedLessonId getrelatedlessonidRemoteActionCompatParcelizer21 = getRelatedLessonId.RemoteActionCompatParcelizer("dec");
        toMagicModuleMetaRepoModel.AudioAttributesCompatParcelizer(getrelatedlessonidRemoteActionCompatParcelizer21, "");
        MediaBrowserCompatCustomActionResultReceiver = getrelatedlessonidRemoteActionCompatParcelizer21;
        getRelatedLessonId getrelatedlessonidRemoteActionCompatParcelizer22 = getRelatedLessonId.RemoteActionCompatParcelizer("plus");
        toMagicModuleMetaRepoModel.AudioAttributesCompatParcelizer(getrelatedlessonidRemoteActionCompatParcelizer22, "");
        getRelatedLessonId getrelatedlessonidRemoteActionCompatParcelizer23 = getRelatedLessonId.RemoteActionCompatParcelizer("minus");
        toMagicModuleMetaRepoModel.AudioAttributesCompatParcelizer(getrelatedlessonidRemoteActionCompatParcelizer23, "");
        getRelatedLessonId getrelatedlessonidRemoteActionCompatParcelizer24 = getRelatedLessonId.RemoteActionCompatParcelizer("not");
        toMagicModuleMetaRepoModel.AudioAttributesCompatParcelizer(getrelatedlessonidRemoteActionCompatParcelizer24, "");
        getRelatedLessonId getrelatedlessonidRemoteActionCompatParcelizer25 = getRelatedLessonId.RemoteActionCompatParcelizer("unaryMinus");
        toMagicModuleMetaRepoModel.AudioAttributesCompatParcelizer(getrelatedlessonidRemoteActionCompatParcelizer25, "");
        getRelatedLessonId getrelatedlessonidRemoteActionCompatParcelizer26 = getRelatedLessonId.RemoteActionCompatParcelizer("unaryPlus");
        toMagicModuleMetaRepoModel.AudioAttributesCompatParcelizer(getrelatedlessonidRemoteActionCompatParcelizer26, "");
        getRelatedLessonId getrelatedlessonidRemoteActionCompatParcelizer27 = getRelatedLessonId.RemoteActionCompatParcelizer("times");
        toMagicModuleMetaRepoModel.AudioAttributesCompatParcelizer(getrelatedlessonidRemoteActionCompatParcelizer27, "");
        getRelatedLessonId getrelatedlessonidRemoteActionCompatParcelizer28 = getRelatedLessonId.RemoteActionCompatParcelizer(TtmlNode.TAG_DIV);
        toMagicModuleMetaRepoModel.AudioAttributesCompatParcelizer(getrelatedlessonidRemoteActionCompatParcelizer28, "");
        getRelatedLessonId getrelatedlessonidRemoteActionCompatParcelizer29 = getRelatedLessonId.RemoteActionCompatParcelizer("mod");
        toMagicModuleMetaRepoModel.AudioAttributesCompatParcelizer(getrelatedlessonidRemoteActionCompatParcelizer29, "");
        getRelatedLessonId getrelatedlessonidRemoteActionCompatParcelizer30 = getRelatedLessonId.RemoteActionCompatParcelizer("rem");
        toMagicModuleMetaRepoModel.AudioAttributesCompatParcelizer(getrelatedlessonidRemoteActionCompatParcelizer30, "");
        getRelatedLessonId getrelatedlessonidRemoteActionCompatParcelizer31 = getRelatedLessonId.RemoteActionCompatParcelizer("rangeTo");
        toMagicModuleMetaRepoModel.AudioAttributesCompatParcelizer(getrelatedlessonidRemoteActionCompatParcelizer31, "");
        onAddQueueItem = getrelatedlessonidRemoteActionCompatParcelizer31;
        getRelatedLessonId getrelatedlessonidRemoteActionCompatParcelizer32 = getRelatedLessonId.RemoteActionCompatParcelizer("rangeUntil");
        toMagicModuleMetaRepoModel.AudioAttributesCompatParcelizer(getrelatedlessonidRemoteActionCompatParcelizer32, "");
        onCustomAction = getrelatedlessonidRemoteActionCompatParcelizer32;
        getRelatedLessonId getrelatedlessonidRemoteActionCompatParcelizer33 = getRelatedLessonId.RemoteActionCompatParcelizer("timesAssign");
        toMagicModuleMetaRepoModel.AudioAttributesCompatParcelizer(getrelatedlessonidRemoteActionCompatParcelizer33, "");
        getRelatedLessonId getrelatedlessonidRemoteActionCompatParcelizer34 = getRelatedLessonId.RemoteActionCompatParcelizer("divAssign");
        toMagicModuleMetaRepoModel.AudioAttributesCompatParcelizer(getrelatedlessonidRemoteActionCompatParcelizer34, "");
        getRelatedLessonId getrelatedlessonidRemoteActionCompatParcelizer35 = getRelatedLessonId.RemoteActionCompatParcelizer("modAssign");
        toMagicModuleMetaRepoModel.AudioAttributesCompatParcelizer(getrelatedlessonidRemoteActionCompatParcelizer35, "");
        getRelatedLessonId getrelatedlessonidRemoteActionCompatParcelizer36 = getRelatedLessonId.RemoteActionCompatParcelizer("remAssign");
        toMagicModuleMetaRepoModel.AudioAttributesCompatParcelizer(getrelatedlessonidRemoteActionCompatParcelizer36, "");
        getRelatedLessonId getrelatedlessonidRemoteActionCompatParcelizer37 = getRelatedLessonId.RemoteActionCompatParcelizer("plusAssign");
        toMagicModuleMetaRepoModel.AudioAttributesCompatParcelizer(getrelatedlessonidRemoteActionCompatParcelizer37, "");
        getRelatedLessonId getrelatedlessonidRemoteActionCompatParcelizer38 = getRelatedLessonId.RemoteActionCompatParcelizer("minusAssign");
        toMagicModuleMetaRepoModel.AudioAttributesCompatParcelizer(getrelatedlessonidRemoteActionCompatParcelizer38, "");
        getKycMessage.IconCompatParcelizer(getrelatedlessonidRemoteActionCompatParcelizer20, getrelatedlessonidRemoteActionCompatParcelizer21, getrelatedlessonidRemoteActionCompatParcelizer26, getrelatedlessonidRemoteActionCompatParcelizer25, getrelatedlessonidRemoteActionCompatParcelizer24, getrelatedlessonidRemoteActionCompatParcelizer16);
        MediaControllerCompatMediaControllerImplApi21ExtraBinderRequestResultReceiver = getKycMessage.IconCompatParcelizer(getrelatedlessonidRemoteActionCompatParcelizer26, getrelatedlessonidRemoteActionCompatParcelizer25, getrelatedlessonidRemoteActionCompatParcelizer24, getrelatedlessonidRemoteActionCompatParcelizer16);
        Set<getRelatedLessonId> setIconCompatParcelizer = getKycMessage.IconCompatParcelizer(getrelatedlessonidRemoteActionCompatParcelizer27, getrelatedlessonidRemoteActionCompatParcelizer22, getrelatedlessonidRemoteActionCompatParcelizer23, getrelatedlessonidRemoteActionCompatParcelizer28, getrelatedlessonidRemoteActionCompatParcelizer29, getrelatedlessonidRemoteActionCompatParcelizer30, getrelatedlessonidRemoteActionCompatParcelizer31, getrelatedlessonidRemoteActionCompatParcelizer32);
        write = setIconCompatParcelizer;
        getKycMessage.RemoteActionCompatParcelizer(getKycMessage.RemoteActionCompatParcelizer(setIconCompatParcelizer, getKycMessage.IconCompatParcelizer(getrelatedlessonidRemoteActionCompatParcelizer13, getrelatedlessonidRemoteActionCompatParcelizer14, getrelatedlessonidRemoteActionCompatParcelizer15, getrelatedlessonidRemoteActionCompatParcelizer16, getrelatedlessonidRemoteActionCompatParcelizer17, getrelatedlessonidRemoteActionCompatParcelizer18, getrelatedlessonidRemoteActionCompatParcelizer19)), getKycMessage.IconCompatParcelizer(getrelatedlessonidRemoteActionCompatParcelizer4, getrelatedlessonidRemoteActionCompatParcelizer6, getrelatedlessonidRemoteActionCompatParcelizer5));
        IconCompatParcelizer = getKycMessage.IconCompatParcelizer(getrelatedlessonidRemoteActionCompatParcelizer33, getrelatedlessonidRemoteActionCompatParcelizer34, getrelatedlessonidRemoteActionCompatParcelizer35, getrelatedlessonidRemoteActionCompatParcelizer36, getrelatedlessonidRemoteActionCompatParcelizer37, getrelatedlessonidRemoteActionCompatParcelizer38);
        getKycMessage.IconCompatParcelizer(getrelatedlessonidRemoteActionCompatParcelizer, getrelatedlessonidRemoteActionCompatParcelizer2, getrelatedlessonidRemoteActionCompatParcelizer3);
    }
}
